<!doctype html>
<html class="no-js" lang="tr" xmlns="http://www.w3.org/1999/xhtml">
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
  <meta charset="utf-8">

  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">

  <!-- search engine block -->
  <meta name="robots" content="noindex">
  <meta name="googlebot" content="noindex">

  <!-- seo -->
  <meta name="author" content="">
  <meta name="copyright" content="" />
  <meta name="description" content="">
  <meta name="keywords" content="">

  <!-- google plus -->
  <link rel="author" href=""/>
  <link rel="publisher" href=""/>
  <!-- open graph & facebook -->
  <meta property="og:title" content="">
  <meta property="og:type" content="website">
  <meta property="og:locale" content="tr">
  <meta property="og:site_name" content="">
  <meta property="og:image" content="">
  <meta property="og:description" content="" >
  <meta property="og:url" content="" />
  <meta property="fb:page_id" content="" />
  <!-- twitter -->
  <meta property="twitter:account_id" content="" />
  <meta name="twitter:site" content="@">
  <meta name="twitter:creator" content="@">
  <meta name="twitter:card" content="summary">
  <meta name="twitter:url" content="">
  <meta name="twitter:title" content="">
  <meta name="twitter:description" content="">
  <meta name="twitter:image" content="">

  <!-- favicon -->
  <link rel="shortcut icon" href="img/favicon/favicon.ico" type="image/x-icon">
  <link rel="icon" href="img/favicon/favicon.png">
  <link rel="icon" sizes="57x57" href="img/favicon/favicon-32x32.png">
  <link rel="icon" sizes="57x57" href="img/favicon/favicon-57x57.png">
  <link rel="icon" sizes="72x72" href="img/favicon/favicon-72x72.png">
  <link rel="icon" sizes="76x76" href="img/favicon/favicon-76x76.png">
  <link rel="icon" sizes="114x114" href="img/favicon/favicon-114x114.png">
  <link rel="icon" sizes="120x120" href="img/favicon/favicon-120x120.png">
  <link rel="icon" sizes="144x144" href="img/favicon/favicon-144x144.png">
  <link rel="icon" sizes="152x152" href="img/favicon/favicon-152x152.png">
  <meta name="msapplication-TileColor" content="#FFFFFF">
  <meta name="msapplication-TileImage" content="img/favicon/favicon-144x144.png">
  <meta name="application-name" content="Blank">

  <title>Blank</title>

  <?php include("_scripts.inc"); ?>

</head>
<body>
