<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html class="no-js" lang="tr" xmlns="http://www.w3.org/1999/xhtml">
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
  <meta charset="utf-8">
  <meta name="description" content="">
  <meta name="author" content="">
  <meta name="robots" content="noindex">
  <meta name="googlebot" content="noindex">

  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">

  <!-- favicon -->
  <link rel="shortcut icon" href="img/favicon/favicon.ico" type="image/x-icon">
  <link rel="icon" href="img/favicon/favicon.png">
  <link rel="icon" sizes="57x57" href="img/favicon/favicon-32x32.png">
  <link rel="icon" sizes="57x57" href="img/favicon/favicon-57x57.png">
  <link rel="icon" sizes="72x72" href="img/favicon/favicon-72x72.png">
  <link rel="icon" sizes="76x76" href="img/favicon/favicon-76x76.png">
  <link rel="icon" sizes="114x114" href="img/favicon/favicon-114x114.png">
  <link rel="icon" sizes="120x120" href="img/favicon/favicon-120x120.png">
  <link rel="icon" sizes="144x144" href="img/favicon/favicon-144x144.png">
  <link rel="icon" sizes="152x152" href="img/favicon/favicon-152x152.png">
  <meta name="msapplication-TileColor" content="#FFFFFF">
  <meta name="msapplication-TileImage" content="img/favicon/favicon-144x144.png">
  <meta name="application-name" content="Blank">

  <title>Blank</title>

  <!--[if lt IE 9]>
    <script type="text/javascript" src="js/html5shiv.js"></script>
    <script type="text/javascript" src="js/modernizr-2.6.2-respond-1.1.0.min.js"></script>
    <script type="text/javascript" src="js/old-browsers.js"></script>
  <![endif]-->

  <!-- fonts -->

  <?php include("_scripts.inc"); ?>

</head>
<body>
