  <!--[if lt IE 10]>
    <script type="text/javascript" src="js/old-browsers.js"></script>
  <![endif]-->
  <script type="text/javascript">
    document.getElementsByTagName('html')[0].setAttribute("data-browser", navigator.userAgent);
    if(/MSIE 1/.test(navigator.userAgent)) {
      document.write('<script src="js//ie-console-fix.js"><\/script>');
      document.write('<script src="js//html5shiv.js"><\/script>');
      document.write('<script src="js//modernizr.min.js"><\/script>');
    }
  </script>

  <!-- fonts -->

  <!-- css -->
  <link rel="stylesheet" type="text/css" href="css/font-awesome.css" />
  <link rel="stylesheet" type="text/css" href="css/bootstrap.css" />
  <link rel="stylesheet" type="text/css" href="css/style.css" />

  <!-- require.js -->
  <!--<script type="text/javascript" data-main="js/config" src="js/lib/require.min.js"></script>-->

  <!-- jquery -->
  <!--<script type="text/javascript" src="//ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>-->
  <!--<script>window.jQuery || document.write('<script src="js//jquery.min.js"><\/script>')</script>-->
  <script type="text/javascript" src="js/jquery.min.js"></script>
  <script type="text/javascript" src="js/bootstrap.min.js"></script>
  <script type="text/javascript" src="js/main.js"></script>