
  <!-- css -->
  <link rel="stylesheet" type="text/css" href="css/font-awesome.css" />
  <link rel="stylesheet" type="text/css" href="css/bootstrap.css" />
  <link rel="stylesheet" type="text/css" href="css/style.css" />


  <!-- jquery -->
  <!-- <script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script> -->
  <!--  <script>window.jQuery || document.write('<script src="js//jquery.min.js"><\/script>')</script> -->
  <script type="text/javascript" src="js/jquery.min.js"></script>
  <script type="text/javascript" src="js/bootstrap.js"></script>

  <!-- js -->
  <script type="text/javascript" src="js/main.js"></script>